### ISSUE TITLE
Using Box in Link<T> is superfluous?

### ISSUE THREAD

**Issue by tmillican** [cmooneycollett/ads-sandbox#7]
From you article:

```Rust
type Link<T> = Option<Rc<RefCell<Box<Node<T>>>>>;
```

I am admittedly very new to Rust, so I might be missing something. But as I understand it, `Rc` always heap allocates its value (via the internal `RcBox` struct). In which case, the `RefCell` is already heap-allocated, and there's no reason to box the `Node<T>`.

**Comment by cmooneycollett** [comment]
Hi @tmillican - great pickup with this issue. I've implemented a change in #8 to simplify the Link<T> type by removing the unnecessary usage of the Box type.
